-- DML Daten

USE videothek;

DELETE FROM `filmen`;

INSERT INTO `filmen` (`id`, `title`, `year`, `runtime`, `genre`, `director`, `actors`, `plot`, `language`, `country`, `poster`,  `imdbid`) VALUES (1, 'Memories of Murder', '2003', '132 min', 'Crime, Drama, Mystery', 'Joon-ho Bong',  'Kang-ho Song, Sang-kyung Kim, Roe-ha Kim, Jae-ho Song', 'In 1986, in the province of Gyunggi, in South Korea, a second young and beautiful woman is found dead, raped and tied and gagged with her underwear. Detective Park Doo-Man and Detective Cho...', 'Korean, English', 'South Korea', 'https://images-na.ssl-images-amazon.com/images/M/MV5BZWYyYTk5ODQtNjFjZi00ZDFlLWEwNGEtNGQwZTdmYWRhNmU3L2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg',  'tt0353969'), (2, 'The Shawshank Redemption', '1994',  '142 min', 'Crime, Drama', 'Frank Darabont', 'Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 'English', 'USA', 'https://images-na.ssl-images-amazon.com/images/M/MV5BODU4MjU4NjIwNl5BMl5BanBnXkFtZTgwMDU2MjEyMDE@._V1_SX300.jpg', 'tt0111161'),
(3, 'The Godfather', '1972', '175 min', 'Crime, Drama', 'Francis Ford Coppola', 'Marlon Brando, Al Pacino, James Caan, Richard S. Castellano', 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.', 'English, Italian, Latin', 'USA', 'https://images-na.ssl-images-amazon.com/images/M/MV5BZTRmNjQ1ZDYtNDgzMy00OGE0LWE4N2YtNTkzNWQ5ZDhlNGJmL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',  'tt0068646'),(4, '12 Angry Men', '1957',  '96 min', 'Crime, Drama', 'Sidney Lumet', 'Martin Balsam, John Fiedler, Lee J. Cobb, E.G. Marshall', 'A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.', 'English', 'USA', 'https://images-na.ssl-images-amazon.com/images/M/MV5BODQwOTc5MDM2N15BMl5BanBnXkFtZTcwODQxNTEzNA@@._V1_SX300.jpg', 'tt0050083'),
(5, 'The Dark Knight', '2008', '152 min', 'Action, Crime, Drama', 'Christopher Nolan', 'Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine', 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, the caped crusader must come to terms with one of the greatest psychological tests of his ability to fight injustice.', 'English, Mandarin', 'USA, UK', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg', 'tt0468569'),
(6, 'The Godfather: Part II', '1974',  '202 min', 'Crime, Drama', 'Francis Ford Coppola', 'Al Pacino, Robert Duvall, Diane Keaton, Robert De Niro', 'The early life and career of Vito Corleone in 1920s New York is portrayed while his son, Michael, expands and tightens his grip on the family crime syndicate.', 'English, Italian, Spanish, Latin, Sicilian', 'USA',' https://images-na.ssl-images-amazon.com/images/M/MV5BMjZiNzIxNTQtNDc5Zi00YWY1LThkMTctMDgzYjY4YjI1YmQyL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'tt0071562');

DELETE FROM `kunde`;

INSERT INTO `kunde` (`first_name`,`last_name`,`age`,`street`,`hause_number`,`postal_code`,`city`,`phone`,`mobile`,`email`) VALUES ('Mark','Philips','24','Juliusstrasse','30','12051','Berlin','030-0000000','015690293847','mark.philips@gmx.de'),
('Joana','Castro','30','Friedrischstrasse','27','10151','Berlin','030-7898133','015683829102','joana.castro@gmx.de'),
('John','Layfield','47','Warschauerstrasse','13','10251','Berlin','030-0000000','015739333092','thejayman@gmail.com'),
('Akira','Takeshi','33','Warschauerstrasse','24','10251','Berlin','030-77783902','0158912135674','super.special@gmx.de'),
('Leonel','Rico','18','Alexanderstrasse','18','13151','Berlin','030-0000000','015490112283','thebestone23@gmx.de');
